framework:
    messenger:
        transports:
            async:
                options:
                    consumer: '%env(HOSTNAME)%'
            low_priority:
                options:
                    consumer: '%env(HOSTNAME)%'
