url: ""
compatibility_date: "2026-08-02"
docker:
  php:
    version: "8.5"
environments:
  local:
    type: docker
    url: http://127.0.0.1:8000

deployment:
  extension-management:
    enabled: true
    force-update:
      - JvMarketConfiguration
      - JvCms
      - JvImport