url: ""
compatibility_date: "2026-08-02"
docker:
  php:
    version: "8.5"
environments:
  local:
    type: docker
    url: http://127.0.0.1:8000

deployment:
  extension-management:
    enabled: true
    force-update:
      - JvMarketConfiguration
      - JvCms
      - JvImport
  hooks:
    post:
      - title: Configure JVMöbel sales channels
        script: bin/console jv:markets:bootstrap --no-interaction
      - title: Configure CosmoShop import profiles
        script: bin/console jv:catalog:bootstrap-import-profiles --no-interaction
      - title: Register project scheduled tasks
        script: bin/console scheduled-task:register --no-interaction
