#!/bin/sh

set -eu

if [ "${SHOPWARE_INITIAL_INSTALL:-0}" = "1" ]; then
    php bin/console system:install \
        --force \
        --shop-name="${SHOPWARE_SHOP_NAME:?SHOPWARE_SHOP_NAME is required}" \
        --shop-email="${SHOPWARE_SHOP_EMAIL:?SHOPWARE_SHOP_EMAIL is required}" \
        --shop-locale=de-DE \
        --shop-currency=EUR \
        --skip-first-run-wizard \
        --no-interaction
fi

php bin/console database:migrate --all --no-interaction
php bin/console plugin:refresh
php bin/console plugin:install --activate --clearCache --no-interaction JvMarketConfiguration JvCms JvImport
php bin/console scheduled-task:register --no-interaction
php bin/console cache:clear --no-interaction
